name: Gaming Site CI
on: 
  workflow_dispatch: # Allows manual start
  push:
    branches: [ main, deploy ] # Runs automatically on push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Start Containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Run Tests
        run: |
          sudo apt-get install xvfb
          xvfb-run --auto-servernum npm test -- --env chrome
